services:
  bot:
    build:
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    container_name: discord-recording-bot
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py

  dev:
    build:
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    container_name: discord-recording-bot-dev
    env_file:
      - .env
    environment:
      - MODEL_SIZE=small
    volumes:
      - .:/app
    working_dir: /app
    tty: true
