services:
  bot:
    build:
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    env_file:
      - .env
    volumes:
      - .:/app
      - ${HOME}/.huggingface:/root/.cache/huggingface
    working_dir: /app
