services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    env_file:
      - .env
    volumes:
      - .:/app
      - ${HOME}/.huggingface:/root/.cache/huggingface
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    env_file:
      - .env
    volumes:
      - .:/app
      - ${HOME}/.huggingface:/root/.cache/huggingface
    ports:
      - "9876:9876"
    working_dir: /app
    command: cli.py websocket
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
