FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04


RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3.11 \
    python3-pip \
    ffmpeg \
    libopus-dev \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN python3.11 -m pip install --upgrade pip \
    && python3.11 -m pip install -r requirements.txt

ENTRYPOINT [ "python3.11" ]
CMD [ "main.py" ]
