services:
  dev:
    build:
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    container_name: discord-recording-bot-dev
    env_file:
      - .env
    environment:
      - MODEL_SIZE=small
    volumes:
      - .:/app
      - ${HOME}/.huggingface:/root/.cache/huggingface
    working_dir: /app
    tty: true
